export const cardsData = [
  {
    id: 1,
    title: "Task 1",
    datetime: "16/9/2022 23:51 hs.",
    creator: "Axel Paz",
    description: "Des 1",
    type: "new",
    priority: "low",
  },
  {
    id: 2,
    title: "Task 2 ",
    datetime: "16/9/2022 23:51 hs.",
    creator: "Axel Paz",
    description: "Des 2",
    type: "InProcess",
    priority: "medium",
  },
  {
    id: 3,
    title: "Task 3",
    datetime: "16/9/2022 23:51 hs.",
    creator: "Axel Paz",
    description: "Des 3",
    type: "InProcess",
    priority: "high",
  },
  {
    id: 4,
    title: "Task 4",
    datetime: "16/9/2022 23:51 hs.",
    creator: "Victor Gimenez",
    description: "Des 4",
    type: "InProcess",
    priority: "low",
  },
  {
    id: 5,
    title: "Task 5",
    datetime: "16/9/2022 23:51 hs.",
    creator: "Emilio",
    description: "Des 5",
    type: "new",
    priority: "low",
  },
  {
    id: 6,
    title: "Task 6",
    datetime: "16/9/2022 23:51 hs.",
    creator: "Lenny",
    description: "Des 6",
    type: "finished",
    priority: "high",
  },
  {
    id: 7,
    title: "Task 7",
    datetime: "16/9/2022 23:51 hs.",
    creator: "Axel Paz",
    description: "Des 7",
    type: "InProcess",
    priority: "medium",
  },
];
